import drawables from "../../../app/drawables";

/**
 * @author Nguyễn Đức Lực
 * @email lucnd@binhanh.vn
 * @create date 2018-09-07 01:42:11
 * @modify date 2018-09-07 01:42:11
 * @desc [quản lý resource ảnh]
*/

export const icons = {
	splash_screen:null,
	//Icon chung
	ic_car_traking: {uri : 'ic_car_traking.png'},
	ic_car_traking_uri: {uri:'ic_car_traking'},
	ic_phone: require('./drawable/general/ic_phone.png'),
	ic_mail: require('./drawable/general/ic_mail.png'),
	ic_person: require('./drawable/general/ic_person.png'),
	ic_sale: require('./drawable/general/ic_sale.png'),
	ic_setting_flagen: require('./drawable/general/ic_setting_flagen.png'),
	ic_setting_flagvn: require('./drawable/general/ic_setting_flagvn.png'),

	book_bkg: require('./drawable/book_bkg.png'),
	ic_address_custom: require('./drawable/ic_address_custom.png'),
	ic_arrow_back: require('./drawable/ic_arrow_back.png'),
	ic_flagen: require('./drawable/ic_flagen.png'),
	ic_flagvn: require('./drawable/ic_flagvn.png'),
	ic_key: require('./drawable/ic_key.png'),

	ic_marker_start: {uri:'ic_marker_start'},

	ic_marker_end: {uri:'ic_marker_end'},


	ic_marker_end_uri: {uri:'ic_marker_end'},
	ic_marker_start_uri: {uri:'ic_marker_start'},

	// ic_marker_start_small: require('./drawable/ic_marker_start_small.png'),
	ic_menu_about: require('./drawable/ic_menu_about.png'),
	ic_menu_book: require('./drawable/ic_menu_book.png'),
	ic_menu_feedback: require('./drawable/ic_menu_feedback.png'),
	ic_menu_help: require('./drawable/ic_menu_help.png'),
	ic_menu_other: require('./drawable/ic_menu_other.png'),
	ic_menu_promotion: require('./drawable/ic_menu_promotion.png'),
	ic_edit: require('./drawable/ic_edit.png'),
	ic_date: require('./drawable/ic_date.png'),
	ic_distance: require('./drawable/ic_distance.png'),
	ic_price: require('./drawable/ic_price.png'),

	ic_menu: require('./drawable/ic_menu.png'),
	ic_type_4_cho_nho: require('./drawable/ic_type_4_cho_nho.png'),
	ic_type_4_cho: require('./drawable/ic_type_4_cho.png'),
	ic_type_7_cho: require('./drawable/ic_type_7_cho.png'),
	ic_type_tatca: require('./drawable/ic_type_tatca.png'),
	ic_user_defatlt: require('./drawable/ic_user_defatlt.png'),
	tick: require('./drawable/tick.png'),

	// History
	ic_dollar: require('./drawable/history/ic_dollar.png'),
	ic_menu_tracking: require('./drawable/history/ic_menu_tracking.png'),
	ic_history_time: require('./drawable/history/ic_history_time.png'),

	// // Rating
	ic_star: require('./drawable/ic_star.png'),

	//About
	about_logo: require('./drawable/logo_about.png'),
	about_share: require('./drawable/ic_share.png'),
	about_rate: require('./drawable/ic_favorite_add.png'),
	//Feedback
	feedback_hotline: require('./drawable/ic_phone.png'),
	feedback_send: require('./drawable/ic_sent.png'),

	// =================================
	ic_alarm: require('./drawable/ic_alarm.png'),
	ic_arrow_bottom: require('./drawable/ic_arrow_bottom.png'),
	ic_arrow_left: require('./drawable/ic_arrow_left.png'),
	ic_arrow_right: require('./drawable/ic_arrow_right.png'),
	ic_attention: require('./drawable/ic_attention.png'),
	ic_bike_near: require('./drawable/ic_bike_near.png'),
	ic_booking_sent: require('./drawable/ic_booking_sent.png'),
	ic_call: require('./drawable/ic_call.png'),
	ic_call_green: require('./drawable/ic_call_green.png'),
	ic_call_header: require('./drawable/ic_call_header.png'),
	ic_cancel: require('./drawable/ic_cancel.png'),
	ic_car: require('./drawable/ic_car.png'),
	ic_car_history: require('./drawable/ic_car_history.png'),
	ic_check: require('./drawable/ic_check.png'),
	ic_check_box: require('./drawable/ic_check_box.png'),
	ic_confirm_note: require('./drawable/ic_confirm_note.png'),
	ic_confirm_schedule: require('./drawable/ic_confirm_schedule.png'),
	ic_contract_car: require('./drawable/ic_contract_car.png'),
	ic_delete: require('./drawable/ic_delete.png'),
	ic_dislike: require('./drawable/ic_dislike.png'),
	ic_done: require('./drawable/ic_done.png'),
	// ic_edit: require("./drawable/ic_edit.png"),
	ic_estimation: require('./drawable/ic_estimation.png'),
	ic_estimation_large: require('./drawable/ic_estimation_large.png'),
	ic_favorite_add: require('./drawable/ic_favorite_add.png'),
	ic_feedback: require('./drawable/ic_feedback.png'),
	ic_gps: require('./drawable/ic_gps.png'),
	ic_header_setting: require('./drawable/ic_header_setting.png'),
	ic_help_header: require('./drawable/ic_help_header.png'),
	ic_home: require('./drawable/ic_home.png'),
	ic_image_remove: require('./drawable/ic_image_remove.png'),
	ic_like: require('./drawable/ic_like.png'),
	ic_location: require('./drawable/ic_location.png'),
	ic_menu_bike: require('./drawable/ic_menu_bike.png'),
	ic_menu_hotline: require('./drawable/ic_menu_hotline.png'),
	ic_menu_logout: require('./drawable/ic_menu_logout.png'),
	ic_menu_setting: require('./drawable/ic_menu_setting.png'),
	ic_message: require('./drawable/ic_message.png'),
	ic_message_new: require('./drawable/ic_message_new.png'),
	ic_my_location: require('./drawable/ic_my_location.png'),
	ic_news_gray: require('./drawable/ic_news_gray.png'),
	ic_not_car: require('./drawable/ic_not_car.png'),
	ic_plus: require('./drawable/ic_plus.png'),
	ic_rate: require('./drawable/ic_rate.png'),
	ic_rate_good: require('./drawable/ic_rate_good.png'),
	ic_remove: require('./drawable/ic_remove.png'),
	ic_search: require('./drawable/ic_search.png'),
	ic_search_address: require('./drawable/ic_search_address.png'),
	ic_search_header: require('./drawable/ic_search_header.png'),
	ic_selected_album: require('./drawable/ic_selected_album.png'),
	ic_selected_camera: require('./drawable/ic_selected_camera.png'),
	ic_sent: require('./drawable/ic_sent.png'),
	ic_share: require('./drawable/ic_share.png'),
	ic_share_booking: require('./drawable/ic_share_booking.png'),
	ic_time: require('./drawable/ic_time.png'),
	ic_time_history: require('./drawable/ic_time_history.png'),
	ic_warning: require('./drawable/ic_warning.png'),
	ic_warning_new: require('./drawable/ic_warning_new.png'),
	ic_working: require('./drawable/ic_working.png'),
	logo_about: require('./drawable/logo_about.png'),
	powered_by_google: require('./drawable/powered_by_google.png'),

	anim_book_one: require('./drawable/anim_book_one.png'),
	anim_book_three: require('./drawable/anim_book_three.png'),
	anim_book_two: require('./drawable/anim_book_two.png'),
	help_bkg: require('./drawable/help_bkg.png'),
	help_estimate_one: require('./drawable/help_estimate_one.png'),
	help_estimate_two: require('./drawable/help_estimate_two.png'),
	help_first_one: require('./drawable/help_first_one.png'),
	help_first_three: require('./drawable/help_first_three.png'),
	help_first_two: require('./drawable/help_first_two.png'),
	ic_any_center: require('./drawable/ic_any_center.png'),
	ic_arrow_cartype: require('./drawable/ic_arrow_cartype.png'),
	ic_arrow_center: require('./drawable/ic_arrow_center.png'),
	ic_arrow_circle_menu: require('./drawable/ic_arrow_circle_menu.png'),
	ic_fare: require('./drawable/ic_fare.png'),
	ic_help_item: require('./drawable/ic_help_item.png'),
	ic_logo_about: require('./drawable/ic_logo_about.png'),
	ic_marker_est: require('./drawable/ic_marker_est.png'),
	ic_not_support_area: require('./drawable/ic_not_support_area.png'),
	ic_notify: require('./drawable/ic_notify.png'),
	ic_oval: require('./drawable/ic_oval.png'),
	ic_oval_gray: require('./drawable/ic_oval_gray.png'),
	ic_oval_small: require('./drawable/ic_oval_small.png'),
	ic_realtime_airport: require('./drawable/ic_realtime_airport.png'),
	ic_tabsany_active: require('./drawable/ic_tabsany_active.png'),
	ic_taxi_type_all: require('./drawable/ic_taxi_type_all.png'),
	ic_toast_bottom: require('./drawable/ic_toast_bottom.png'),
	ic_toast_header: require('./drawable/ic_toast_header.png'),
	ic_type_16_cho: require('./drawable/ic_type_16_cho.png'),
	ic_type_4_cho_hd: require('./drawable/ic_type_4_cho_hd.png'),
	ic_type_4_cho_km: require('./drawable/ic_type_4_cho_km.png'),
	ic_type_4_cho_nho_hd: require('./drawable/ic_type_4_cho_nho_hd.png'),
	ic_type_7_cho_hd: require('./drawable/ic_type_7_cho_hd.png'),
	ic_type_7_cho_km: require('./drawable/ic_type_7_cho_km.png'),
	ic_type_7_cho_nho: require('./drawable/ic_type_7_cho_nho.png'),
	ic_type_bike: require('./drawable/ic_type_bike.png'),
	ic_type_shipper: require('./drawable/ic_type_shipper.png'),
	ic_type_tatca_long: require('./drawable/ic_type_tatca_long.png'),
	ic_user_menu: require('./drawable/ic_user_menu.png'),
	moto_thanhdong_logo: require('./drawable/moto_thanhdong_logo.png'),
	promotion_bkg: require('./drawable/promotion_bkg.png'),
	selection_divider: require('./drawable/selection_divider.png'),
	share_booking_disable_bkg: require('./drawable/share_booking_disable_bkg.png'),
	share_booking_enable_bkg: require('./drawable/share_booking_enable_bkg.png'),
	support_bkg: require('./drawable/support_bkg.png'),
	taxi_envang_logo: require('./drawable/taxi_envang_logo.png'),
	taxi_hoaphuong_logo: require('./drawable/taxi_hoaphuong_logo.png'),
	taxi_logo_bkg: require('./drawable/taxi_logo_bkg.png'),
	taxi_staxi_logo: require('./drawable/taxi_staxi_logo.png'),
	taxi_thanhdong_logo: require('./drawable/taxi_thanhdong_logo.png'),
	taxi_vugia_logo: require('./drawable/taxi_vugia_logo.png'),
	transperent: require('./drawable/transperent.png'),
	waiting_time_five: require('./drawable/waiting_time_five.png'),
	waiting_time_four: require('./drawable/waiting_time_four.png'),
	waiting_time_one: require('./drawable/waiting_time_one.png'),
	waiting_time_three: require('./drawable/waiting_time_three.png'),
	waiting_time_two: require('./drawable/waiting_time_two.png'),
	ic_map: require('./drawable/ic_map.png'),

	//menu mới
	ic_history: require('./drawable/ic_history.png'),
	ic_menu_promotions: require('./drawable/ic_menu_promotions.png'),
	ic_menu_notifycationsic_history: require('./drawable/ic_menu_notifycations.png'),
	ic_menu_intro: require('./drawable/ic_menu_intro.png'),
	ic_menu_helps: require('./drawable/ic_menu_helps.png'),
	ic_menu_car: require('./drawable/ic_menu_car.png'),

	...drawables
};

export default {
	...icons,
	...drawables,
}